###

# curl --location --request POST 'localhost:3001/api/login'
#--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NTUyNzYzNzQsImV4cCI6MTY1NTI3Njk3NH0.gE3uUBGa8Wo5VvvwZbFMM_YBf7UBcnkOTklLVPkUuNs'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "username": "test",
#    "password": "test"
#}'
POST localhost:3001/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE2NTUyNzYzNzQsImV4cCI6MTY1NTI3Njk3NH0.gE3uUBGa8Wo5VvvwZbFMM_YBf7UBcnkOTklLVPkUuNs
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

