# syntax=docker/dockerfile:1

FROM node:16.14.2

WORKDIR /api

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install
COPY ["./server/", "./"]

ENV DB_HOST=${{ secrets.DB_HOST }}
ENV DB_USER=${{ secrets.DB_USER }}
ENV DB_PASSWORD=${{ secrets.DB_PASSWORD }}
ENV DB_NAME=my-sku-app

CMD ["node", "app.js"]
