version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo/
    depends_on:
      - mongo


#  backend:
#    image: bluebuug/my-sku-app:backend
#    ports:
#      - "3001:3001"
#    build:
#      context: .
#      dockerfile: Dockerfile.backend
#    environment:
#      CONN_STR: "postgresql://postgres:postgres@db:5432/my-sku-db"
#      KOA_PORT: 3001
#    networks:
#      - mongo-net
#    volumes:
#      - .:/app/server

#  frontend:
#    image: bluebuug/my-sku-app:frontend
#    build:
#      context: .
#      dockerfile: Dockerfile.frontend
#    working_dir: /app
#    networks:
#      - pg-net
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
#networks:
#  mongo-net:
#volumes:
#  mongo-data:

