# syntax=docker/dockerfile:1

FROM node:16.14.2

ENV NODE_ENV=development

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install
COPY . ./

ENV URL=backend-env.eba-72w8ub89.us-west-1.elasticbeanstalk.com

CMD ["npm", "run", "dev"]