version: '3.9'
services:

  backend:
    image: bluebuug/my-sku-app:backend
    ports:
      - "3001:3001"
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    environment:
#      docker compose up -d -e DB_HOST=${{secrets.DB_HOST}} -e DB_USER=${{secrets.DB_USER}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}}
#      DB_HOST: ${{secrets.DB_HOST}}
#      DB_USER: ${{secrets.DB_USER}}
#      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
#      DB_NAME: 'my-sku-app'
      KOA_PORT: 3001
    networks:
      - pg-net
    volumes:
      - .:/app/server

  frontend:
    image: bluebuug/my-sku-app:frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /app
    networks:
      - pg-net
    ports:
      - "3000:3000"
    depends_on:
      - backend
networks:
  pg-net:

