name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Frontend
      run: docker build -f Dockerfile.frontend -t bluebuug/my-sku-app:frontend .
    - name: Push Frontend
      run: docker push bluebuug/my-sku-app:frontend

    - name: Build Backend
      run: docker build -f Dockerfile.backend -t bluebuug/my-sku-app:backend .
    - name: Push Backend
      run: docker push bluebuug/my-sku-app:backend
