name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Frontend
      run: docker build -f Dockerfile.frontend -t bluebuug:frontend .
    - name: Build Backend
      run: docker build -f Dockerfile.backend -t bluebuug:backend .
