name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.backend
        push: true
        platforms: linux/amd64,linux/arm64
        tags: bluebuug/my-sku-app:backend
        secrets: |
          "DB_HOST=${{ secrets.DB_HOST }}"
          "DB_USER=${{ secrets.DB_USER }}"
          "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
#          "github_token=${{ secrets.GITHUB_TOKEN }}"
#    - name: Build Frontend
#      run: docker build
#        -f Dockerfile.frontend
#        -t bluebuug/my-sku-app:frontend .
#    - name: Push Frontend
#      run: docker push bluebuug/my-sku-app:frontend
#
#    - name: Build Backend
#      run: docker build
#        -f Dockerfile.backend
#        -t bluebuug/my-sku-app:backend .
#    - name: Push Backend
#      run: docker push bluebuug/my-sku-app:backend
